# all-playbooks.yml
# Run playbooks sequentially to set up environment
---
  - import_playbook: yum-update.yml
  - import_playbook: install-services.yml
  - import_playbook: setup-app.yml
  - import_playbook: setup-lb.yml
  - import_playbook: check-apache-status.yml